/**
 * ⚠️ DEVELOPMENT / DEMO ROUTE ONLY
 *
 * This endpoint is NOT part of the production pipeline.
 * Blog posts should be generated by the external pipeline and committed to the repo.
 * This route exists for local development and demonstration only.
 */

import { NextRequest, NextResponse } from "next/server";
import { generatePostFromTranscript } from "@/lib/post-generator";

export async function POST(request: NextRequest) {
    if (process.env.NODE_ENV === "production") {
        return NextResponse.json(
            { error: "Post generation is handled by the external pipeline in production." },
            { status: 403 }
        );
    }

    try {
        const { transcript, transcriptFile } = await request.json();

        if (!transcript && !transcriptFile) {
            return NextResponse.json(
                { error: "Provide transcript or transcriptFile." },
                { status: 400 }
            );
        }

        const result = await generatePostFromTranscript(transcript || transcriptFile);
        return NextResponse.json(result);
    } catch (error) {
        console.error("Post generation error:", error);
        return NextResponse.json({ error: "Post generation failed." }, { status: 500 });
    }
}
